### ISSUE TITLE
#Chapter06: NOT NULL constraint failed: posts_post.author_id

### ISSUE THREAD

**Issue by AlexVFornazieri** [brwr/thinkster-django-angular-tutorial#23]
I get this error when creating a new post, apparently the id of the author is not being sent. I did not understand why !?

When I use "author = models.ForeignKey (Account, null = True)" everything works fine, but the author of the post is not identified.

Link repository on GitHub: https://github.com/AlexVFornazieri/thinkster-django-angular-boilerplate

Any suggestions to fix this error?

I thank everyone's attention!

**Comment by brwr** [comment]
There is an indentation error in your posts/views.py file.

**Comment by AlexVFornazieri** [comment]
It works!! Well simply this! I was getting crazy with it ... Thanks for help!
